# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
    goos:
      - linux
archives:
  - replacements:
      linux: Linux
      386: i386
      amd64: x86_64
    files:
      - samples
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

signs:
  - id: signify
    signature: ${artifact}.sig
    cmd: signify
    args: ["-S", "-s", "{{ .Env.HOME }}/.signify/ssh-sentinel.sec", "-m", "${artifact}", "-x", "${artifact}.sig"]
    artifacts: checksum
release:
  prerelease: auto
  mode: keep-existing
#gomod:
#  proxy: true
#  env:
#    - GOPROXY=https://proxy.golang.org,direct
#    - GOSUMDB=sum.golang.org
#    - GOPRIVATE=st2projects.com/ssh-sentinel-server
#  mod: mod
#  gobinary: go
