env_files:
  github_token: .githubtoken
before:
  hooks:
    - go mod tidy
builds:
  - goarch:
      - amd64
    goos:
      - linux

archives:
  - files:
      - samples
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

signs:
  - id: signify
    signature: ${artifact}.sig
    cmd: signify
    args: ["-S", "-s", "{{ .Env.HOME }}/.signify/st2projects-code-signing.sec", "-m", "${artifact}", "-x", "${artifact}.sig"]
    artifacts: checksum
release:
  prerelease: auto
  mode: keep-existing