
### testNormalRequest
POST https://localhost:443/ssh
Content-Type: application/json

{"username": "ben", "api_key": "99cb4e89-c397-4060-a17e-e5284e2f8b54", "principals": ["ben"], "key": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICazCPU7VgxhgZWNXr2bA2nErkFyXRz4IMddcZLDN7MU xxx@aaa"}

> {%
 // Response handler
 client.test("Request was successful", function () {
     client.assert(response.status === 200, "Status was not 200");
     client.assert(response.body.signedKey !== "", "signed key was empty!");
     // let responseBody = JSON.parse(response.body.toString());
     // client.assert(responseBody.signedKey != null, "Signed key was empty / null");
 });
 %}
